apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: webapp-deployment
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:v0
        ports:
        - containerPort: 3000